import 'package:fp/models/LawyerModel.dart';

List<LawyerModel> lawyers = [
  LawyerModel(name: 'علي الخطيب', price: '400', major: 'أسرة'),
  LawyerModel(name: 'أحمد الشرقاوي', price: '450', major: 'مدني'),
  LawyerModel(name: 'محمود العمدة', price: '450', major: 'جنح'),
  LawyerModel(name: 'محمد الشاذلي', price: '500', major: 'جرائم إلكترونية'),
  LawyerModel(name: 'خالد الجمل', price: '500', major: 'عمال'),
  LawyerModel(name: 'محمد عبدالرحمن', price: '500', major: 'تجاري وشركات'),
  LawyerModel(name: 'اسماعيل الحسيني', price: '400', major: 'أسرة'),
  LawyerModel(name: 'عمر الزعبي', price: '400', major: 'مدني'),
  LawyerModel(name: 'نور الدين السيد', price: '450', major: 'جنح'),
  LawyerModel(name: 'محمد العتال', price: '450', major: 'جرائم إلكترونية'),
  LawyerModel(name: 'محمد الغندور', price: '500', major: 'عمال'),
  LawyerModel(name: 'يوسف الفرا', price: '500', major: 'تجاري وشركات'),
  LawyerModel(name: 'محسن الحاج', price: '400', major: 'أسرة'),
  LawyerModel(name: 'رامي الحداد', price: '450', major: 'مدني'),
  LawyerModel(name: 'محمد العوضي', price: '450', major: 'جنح'),
  LawyerModel(name: 'صلاح الدين الباز', price: '500', major: 'جرائم إلكترونية'),
  LawyerModel(name: 'أحمد السيد', price: '400', major: 'عمال'),
  LawyerModel(name: 'رائد البعيو', price: '500', major: 'تجاري وشركات'),
  LawyerModel(name: 'سمير الحج', price: '500', major: 'أسرة'),
  LawyerModel(name: 'محمد الخولي', price: '450', major: 'مدني'),
  LawyerModel(name: 'عبدالرحيم السيد', price: '450', major: 'جنح'),
  LawyerModel(name: 'نور الدين الحلواني', price: '500', major: 'جرائم إلكترونية'),
  LawyerModel(name: 'محمود النوباني', price: '500', major: 'عمال'),
  LawyerModel(name: 'محمد الصاوي', price: '500', major: 'تجاري وشركات'),
  LawyerModel(name: 'ابراهيم السيد', price: '500', major: 'أسرة'),
  LawyerModel(name: 'محمد العبد', price: '450', major: 'مدني'),
  LawyerModel(name: 'زياد السيد', price: '450', major: 'جنح'),
  LawyerModel(name: 'اسماعيل الحريري', price: '500', major: 'جرائم إلكترونية'),
  LawyerModel(name: 'محمد الجمل', price: '500', major: 'عمال'),
  LawyerModel(name: 'عمر الشامي', price: '500', major: 'تجاري وشركات'),
];